# Generated by Django 4.1.13 on 2023-12-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
