# Generated by Django 4.1.13 on 2024-01-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_type_product_tipos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tipos',
            new_name='types',
        ),
    ]
