# Generated by Django 4.1.13 on 2024-01-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_rating_value_rating_unique_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tgs',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
    ]
