# Generated by Django 4.1.13 on 2024-01-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_resource_rename_tgs_product_tags_product_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
